"use client";
import { useState } from "react";
import { useConfirm } from "@/components/confirm";
import type { CreativeConceptView, CreativeProjectDryRunResult } from "@/application/directors/creative/analyze-for-project";
import { messageFromCreativeApiError, type CreativeApiErrorBody } from "./creative-messages";

export function CreativeSection({projectId,initialConcept=null}:{projectId:string;initialConcept?:CreativeConceptView|null}) {
 const confirm=useConfirm();const [dry,setDry]=useState<CreativeProjectDryRunResult|null>(null);const [concept,setConcept]=useState<CreativeConceptView|null>(initialConcept);const [busy,setBusy]=useState<"dry-run"|"execute"|null>(null);const [error,setError]=useState<string|null>(null);const [status,setStatus]=useState<string|null>(null);
 async function check(){if(busy)return;setBusy("dry-run");setError(null);try{const r=await fetch(`/api/director/projects/${projectId}/creative`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"dry-run"})});const d=await r.json() as {dryRun?:CreativeProjectDryRunResult;error?:string};if(!r.ok){setError(d.error??"Vérification impossible.");return}if(d.dryRun){setDry(d.dryRun);setConcept(d.dryRun.existingConcept??concept);setStatus(d.dryRun.executable?"Marketing Plan prêt pour Creative.":"Pré-requis Creative incomplets.");}}catch{setError("Vérification impossible.")}finally{setBusy(null)}}
 async function execute(){if(busy||!dry?.executionAvailable)return;const ok=await confirm({title:"Lancer l’analyse créative ?",message:"Cet appel est payant. Le brief et le Marketing Plan actifs ne seront pas modifiés.",confirmLabel:"Lancer l’analyse"});if(!ok)return;setBusy("execute");setError(null);try{const r=await fetch(`/api/director/projects/${projectId}/creative`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"execute",expectedMarketingPlanRevision:dry.marketingPlanRevision})});const d=await r.json() as CreativeApiErrorBody&{concept?:CreativeConceptView};if(!r.ok){setError(messageFromCreativeApiError(d));return}if(d.concept){setConcept(d.concept);setStatus("Concept créatif enregistré.");}}catch{setError("Analyse créative impossible.")}finally{setBusy(null)}}
 return <section className="mt-10" aria-labelledby="creative-heading"><h2 id="creative-heading" className="text-base font-semibold mb-2">Direction créative</h2><p className="text-sm text-[var(--muted)] mb-4">Le concept créatif est fondé sur le brief et le Marketing Plan actifs.</p><div className="flex flex-wrap gap-3 mb-4"><button type="button" className="btn btn-primary" onClick={check} disabled={busy!=null}>{busy==="dry-run"?"Vérification…":"Vérifier les prérequis"}</button>{dry?.executionAvailable?<button type="button" className="btn btn-ghost" onClick={execute} disabled={busy!=null}>{busy==="execute"?"Analyse…":"Lancer l’analyse créative"}</button>:<button type="button" className="btn btn-ghost" disabled aria-disabled="true">Lancer l’analyse créative — indisponible</button>}</div>{status&&<p className="text-sm text-[var(--muted)] mb-2" role="status">{status}</p>}{error&&<p className="text-sm text-[var(--danger)] mb-2" role="alert">{error}</p>}{dry&&<div className="card p-4 mb-4 text-sm"><p>Dry-run · {dry.executable?"prêt":"non prêt"} · exécution {dry.executionAvailable?"autorisable":"non disponible"}</p>{dry.missingInformation.length>0&&<ul className="list-disc pl-5 text-xs text-[var(--muted)]">{dry.missingInformation.map(x=><li key={x.code}>{x.message}</li>)}</ul>}</div>}{concept&&<dl className="card p-5 grid gap-3 text-sm"><div><dt className="text-[var(--muted)]">Révision</dt><dd>{concept.revision}</dd></div>{concept.title&&<div><dt className="text-[var(--muted)]">Titre</dt><dd>{concept.title}</dd></div>}{concept.logline&&<div><dt className="text-[var(--muted)]">Logline</dt><dd>{concept.logline}</dd></div>}{concept.bigIdea&&<div><dt className="text-[var(--muted)]">Big idea</dt><dd>{concept.bigIdea}</dd></div>}{concept.narrativeApproach&&<div><dt className="text-[var(--muted)]">Approche narrative</dt><dd>{concept.narrativeApproach}</dd></div>}{concept.rhythm&&<div><dt className="text-[var(--muted)]">Rythme</dt><dd>{concept.rhythm}</dd></div>}{concept.emotionalArc&&<div><dt className="text-[var(--muted)]">Arc émotionnel</dt><dd>{concept.emotionalArc}</dd></div>}</dl>}</section>;
}
